<a href="https://colab.research.google.com/github/carlosgilrodrigo/TFM/blob/main/Clustering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importaci√≥n de paquetes
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import matplotlib

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
#Lectura de datos
df = pd.read_csv('/content/drive/MyDrive/TFM/datasetLimpio60.csv', decimal='.')

In [4]:
df

,home_team,away_team,result_full,result_ht,home_passes,home_possession,home_shots,home_shots_on_target,home_touches,away_passes,...,goals_scored_ft_avg_A,goals_conced_ft_avg_A,sg_match_ft_acum_A,goals_scored_ht_avg_A,goals_conced_ht_avg_A,sg_match_ht_acum_A,performance_acum_A,result_match,result_descanso,num_season
0,blackpool,west bromwich albion,2-1,1-0,0.45,0.73,0.59,0.29,0.49,0.14,...,0.21,0.46,0.42,0.00,0.25,0.40,0.33,0,0,1
1,liverpool,manchester city,3-0,3-0,0.42,0.54,0.48,0.29,0.50,0.37,...,0.24,0.18,0.61,0.27,0.07,0.74,0.49,0,0,1
2,manchester united,arsenal,1-0,1-0,0.30,0.43,0.39,0.35,0.36,0.41,...,0.31,0.17,0.62,0.29,0.06,0.66,0.71,0,0,1
3,stoke city,aston villa,2-1,0-1,0.12,0.39,0.48,0.53,0.19,0.26,...,0.00,1.00,0.42,0.00,0.75,0.43,0.00,0,2,1
4,fulham,chelsea,0-0,0-0,0.19,0.30,0.30,0.29,0.29,0.51,...,0.28,0.18,0.64,0.23,0.19,0.49,0.46,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4065,liverpool,brighton and hove albion,0-1,0-0,0.62,0.70,0.25,0.06,0.67,0.29,...,0.20,0.23,0.48,0.20,0.20,0.46,0.40,2,1,11
4066,burnley,leicester city,1-1,1-1,0.21,0.32,0.27,0.41,0.23,0.50,...,0.32,0.14,0.73,0.23,0.10,0.63,0.77,1,1,11
4067,crystal palace,manchester united,0-0,0-0,0.21,0.29,0.18,0.12,0.25,0.53,...,0.32,0.17,0.70,0.23,0.19,0.49,0.74,1,1,11
4068,sheffield united,aston villa,1-0,1-0,0.10,0.16,0.20,0.12,0.13,0.58,...,0.23,0.13,0.64,0.21,0.06,0.66,0.59,0,0,11
4069,newcastle united,liverpool,0-0,0-0,0.08,0.14,0.18,0.12,0.13,0.61,...,0.38,0.28,0.58,0.29,0.25,0.49,0.48,1,1,11